name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]  # Test across multiple Python versions

    steps:
    - uses: actions/checkout@v4  # Check out the repository code
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests with pytest
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} 
        TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }} 
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} 
      run: |
        pytest  --verbose --cov=src --cov-report=xml
    - name: Upload coverage report
      uses: codecov/codecov-action@v4  # Optional: Upload coverage to Codecov
      with:
        file: ./coverage.xml
      if: success()